const INCREASE_ITEM = 'INCREASE_ITEM';
const DECREASE_ITEM = 'DECREASE_ITEM';
const REMOVE_ITEM   = 'REMOVE_ITEM';
const TOTAL_ITEMS = 'TOTAL_ITEMS';
const TOTAL_AMOUNT = 'TOTAL_AMOUNT';
const CLEAR_CART = 'CLEAR_CART'

export  {INCREASE_ITEM, DECREASE_ITEM, REMOVE_ITEM, TOTAL_ITEMS, TOTAL_AMOUNT, CLEAR_CART};
